backend:
  name: github
  repo: ahmadilham-idsrg/ahmadilham-idsrg.github.io
  branch: main
  auth_scope: repo
  local_backend: true

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Home Cards"
            name: "homeCards"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Image URL", name: "image", widget: "string", required: false }
      - file: "content/about-me/_index.md"
        label: "About Me"
        name: "aboutMe"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/lectures/_index.md"
        label: "Lectures"
        name: "lectures"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/research-grants/_index.md"
        label: "Research Grants"
        name: "researchGrants"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/roadmap/_index.md"
        label: "Roadmap"
        name: "roadmap"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/more/_index.md"
        label: "More"
        name: "more"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
